### ISSUE TITLE
nsdperf does not produce result.json on RHELS8.5

### ISSUE THREAD

**Issue by URZ-HD** [IBM/SpectrumScale_NETWORK_READINESS#11]
Hi,
when using this tool on RHELS 8.5 nsdperfTool.py can not parse the Output of 
`ip -s link show <dev>` because of a changed header (Line 287):

Original:
`ipLinkFormat = r"RX: bytes  packets  errors  dropped overrun mcast" \`

Output on RHELS 8.5
`ipLinkFormat = r"RX: bytes  packets  errors  dropped missed  mcast" \`

So the regex should be extended to something like `(overrun|missed)`

best,
Sven

**Comment by TimLindholm98** [comment]
Hi Sven

I fixed it in RHEL 8.6 (shouldnt matter) by changing the regex in the nsdperfTool.py on line 290 to this belovw

`ipLinkFormat = r"RX:\s+bytes\s+packets\s+errors\s+dropped\s+missed\s+mcast" \
             r"\s+\d+\s+\d+\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+TX:\s+bytes\s+" \
             r"packets\s+errors\s+dropped\s+carrier\s+collsns\s+\d+\s+\d+\s+(\d+)" \
            r"\s+(\d+)\s+(\d+)\s+(\d+)"`

The problem is that the spaces is different in newer version of RHEL, I havent done extensive testing but works for me to test the network

**Comment by bolinches** [comment]
https://github.com/IBM/SpectrumScale_NETWORK_READINESS/commit/36811bec8eb833ae7a8978095595156059fa5bd6
