### ISSUE TITLE
"ibv_post_send" message spent Time

### ISSUE THREAD

**Issue by Mingwei-Gu** [IBM/SpectrumScale_NETWORK_READINESS#9]
I want to know how much time does a "ibv_post_send" message spent. Where should I put getTime() method?

**Comment by bolinches** [comment]
I beleive you should run nsdperf directly on debug mode, instead of koet. I will add more data on what this tool is and what does and what does not do. As mentioned, sonsider this a frontend to hide and compare results of nsdperf by hiding and limiting the options of nsdperf. Power users should fall back to nsdperf
